[package]
name = "wlshot"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.19.5"

[dependencies.gtk]
package = "gtk4"
version = "0.8.1"
features = ["v4_14"]

[dependencies.chrono]
version = "0.4.37"

[dependencies.xdg]
version = "2.5.2"
